### PR TITLE
Switched QueueWriteTask to use the AsyncKeyedLock library

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@PraxisMapper

**Comment by MarkCiliaVincenti** [comment]
@PraxisMapper

**Comment by MarkCiliaVincenti** [comment]
@PraxisMapper let me know what your intentions are so I can see whether or not to fix the conflict please.

**Comment by PraxisMapper** [comment]
I don't think I'm going to merge this.

Your library looks good, and this pointed out that I have a couple different places in my code with locks that needed consolidated. I do not want to add an external dependency to my project for this, since I'm not doing anything particularly complicated with locks where your library would be a bigger help.

**Comment by MarkCiliaVincenti** [comment]
OK. Though I'd suggest you at least release inside a finally block in case that AppendAllText throws an exception because then you'd have an issue.

**Pull request closed without merging**
